### ISSUE TITLE
query-replace-interactive removed from Emacs 29

### ISSUE THREAD

**Issue by jdchristensen** [jhpalmieri/ultratex#3]
It's been obsolete since Emacs 24, I think.  `light.el` contains:

```
(defun lc-query-replace-read-args (string regexp-flag)
  (let (from to)
    (if query-replace-interactive
```

which now causes an error.  Since it's been obsolete for so long, the `if` should probably be removed.  But I don't know whether the variable should be assumed to be true or false when making this change.

**Comment by jhpalmieri** [comment]
The default value for the obsolete variable seems to be `nil`, so I think we can just keep the `else` part.
